import React from 'react';
import {Image, View} from 'react-native';
import Svg, {Circle, Defs, RadialGradient, Stop} from 'react-native-svg';

/** Width ÷ height of the mark (tight crop of brand/hassad-logo.png). */
const ASPECT = 1999 / 2115;
const SOURCE = require('../assets/brand/hassad-logo.png');

/**
 * The official Hassad logo, exactly as extracted: black mark, transparent
 * ground. Only place it on light paper — there is no white variant yet.
 * Assets are regenerated by scripts/brand/make-brand-assets.py.
 */
export const HassadLogo = ({size = 56}: {size?: number}) => (
  <Image source={SOURCE} style={{width: Math.round(size * ASPECT), height: size}} resizeMode="contain" accessibilityIgnoresInvertColors />
);

/** The logo pressed into a gold wax seal, so it reads on dark paper too
 * (used to close the verify-email envelope). */
export const BrandSeal = ({size = 56}: {size?: number}) => (
  <View style={{width: size, height: size, alignItems: 'center', justifyContent: 'center'}}>
    <Svg width={size} height={size} viewBox="0 0 56 56" style={{position: 'absolute'}}>
      <Defs>
        <RadialGradient id="wax" cx="38%" cy="32%" r="70%">
          <Stop offset="0" stopColor="#D9B467" />
          <Stop offset="1" stopColor="#A9792C" />
        </RadialGradient>
      </Defs>
      <Circle cx={28} cy={28} r={27} fill="url(#wax)" />
      <Circle cx={28} cy={28} r={22.5} fill="none" stroke="#7E5718" strokeOpacity={0.45} strokeWidth={1} />
    </Svg>
    <HassadLogo size={Math.round(size * 0.5)} />
  </View>
);
